const events = [
  {
    city: "Niksic",
    name: "Tiffany",
    location: "The House pub",
    entry: "Free",
    day: "Utorak",
    date: "21. Maj",
    hours: "22:00",
    img: "img/housePub1.jpg",
    music_performer: "Svirka",
    type_of_music: "Rok muzika",
    reservation: "069/654/334",
  },

  {
    city: "Niksic",
    name: "Sanja Vucic",
    location: "Royal Garden",
    entry: "15€",
    day: "Srijeda",
    date: "05.Jun",
    hours: "20:00",
    img: "img/SanjaVucic.jpg",
    music_performer: "Koncert",
    type_of_music: "Pop muzika",
    reservation: "062/982/162",
  },

  {
    city: "Niksic",
    name: "Sasa Miranovic",
    location: "Stari Jadran Pivnica",
    entry: "Free",
    day: "Cetvrtak",
    date: "23.Maj",
    hours: "21:30",
    img: "img/mikrofon.jpg",
    music_performer: "Svirka",
    type_of_music: "Narodna muzika",
    reservation: "067/245/212",
  },
  {
    city: "Niksic",
    name: "Marella",
    location: "Montenegro Pub",
    entry: "Free",
    day: "Ponedeljak",
    date: "22. Maj",
    hours: "22:00",
    img: "img/marella.jpg",
    music_performer: "DJ",
    type_of_music: "Studentska Zurka",
    reservation: "068/211/867",
  },

  {
    city: "Niksic",
    name: "Dzimi",
    location: "Brick pub",
    entry: "Besplatan",
    day: "Ponedeljak",
    date: "29. Maj",
    hours: "23:00",
    img: "img/brick_pub.jpg",
    music_performer: "Svirka",
    type_of_music: "Narodna muzika",
    reservation: "067/342/111",
  },

  {
    id: 1,
    city: "Niksic",
    name: "Rajo Simonovic",
    location: "Grahovac 1858",
    entry: "Free",
    day: "Utorak",
    date: "06. Jun",
    hours: "15:00",
    img: "img/StariJadran1.jpg",
    music_performer: "Svirka",
    type_of_music: "Narodna muzika",
    reservation: "067/627/098",
  },

  {
    city: "Niksic",
    name: "Dj Funkella",
    location: "House pub",
    entry: "Free",
    day: "Petak",
    date: "17. Maj",
    hours: "22:00",
    img: "img/housePub2.jpg",
    music_performer: "DJ",
    type_of_music: "Rok muzika",
    reservation: "069/356/111",
  },

  {
    city: "Niksic",
    name: "Olivera Mutovic",
    location: "Propaganda",
    entry: "Free",
    day: "Petak",
    date: "17. Maj",
    hours: "20:00",
    img: "img/propaganda1.jpg",
    music_performer: "Svirka",
    type_of_music: "Rok muzika",
    reservation: "069/356/111",
  },

  {
    city: "Niksic",
    name: "DJ Marella",
    location: "Prica caffee",
    entry: "Free",
    day: "Petak",
    date: "31. Maj",
    hours: "22:00",
    img: "img/prica1.jpg",
    music_performer: "Svirka",
    type_of_music: "Pop muzika",
    reservation: "069/298/552",
  },

  {
    city: "Niksic",
    name: "Sasa Matic",
    location: "Exclusive event center",
    entry: "20€",
    day: "Petak",
    date: "07. Jun",
    hours: "20:00",
    img: "img/SasaMatic.jpg",
    music_performer: "Koncert",
    type_of_music: "Narodna muzika",
    reservation: "069/356/111",
  },

  {
    city: "Niksic",
    name: "Milky Wave",
    location: "Bard  caffee",
    entry: "Free",
    day: "Petak",
    date: "17. Maj",
    hours: "21:00",
    img: "img/MilkyWave.jpg",
    music_performer: "Svirka",
    type_of_music: "Rok muzika",
    reservation: "Nema",
  },

  {
    city: "Niksic",
    name: "DJ Nelly",
    location: "Diamond Night club",
    entry: "Free",
    day: "Subota",
    date: "18. Maj",
    hours: "00:00",
    img: "img/diamond1.jpg",
    music_performer: "DJ",
    type_of_music: "Studentska Zurka",
    reservation: "067/342/111",
  },

  {
    city: "Niksic",
    name: "Rudhaman",
    location: "Atrium Bistro",
    entry: "Free",
    day: "Subota",
    date: "18. Maj",
    hours: "21:00",
    img: "img/atrium.jpg",
    music_performer: "Svrika",
    type_of_music: "Narodna muzika",
    reservation: "067/342/111",
  },

  {
    city: "Niksic",
    name: "Talia Band",
    location: "Oktoberfest beer house",
    entry: "Free",
    day: "Subota",
    date: "25. Maj",
    hours: "21:00",
    img: "img/taliaBand.jpg",
    music_performer: "Svirka",
    type_of_music: "Pop muzika",
    reservation: "063/562/211",
  },

  {
    city: "Niksic",
    name: "Sergej Cetkovic",
    location: "Hotel Onogost",
    entry: "20€",
    day: "Subota",
    date: "08.Jun",
    hours: "20:00",
    img: "img/sergej.jpg",
    music_performer: "koncert",
    type_of_music: "Pop muzika",
    reservation: "069/111/106",
  },
  {
    city: "Niksic",
    name: "Dilan Puzovic",
    location: "Pivnica",
    entry: "Besplatan",
    day: "Subota ",
    date: "08.Jun",
    hours: "00:00",
    img: "img/dilan.jpg",
    music_performer: "Svirka",
    type_of_music: "Narodna muzika",
    reservation: "067/234/227",
  },

  {
    city: "Niksic",
    name: "DJ Veljko",
    location: "Greenwood pub",
    entry: "Besplatan",
    day: "Subota",
    date: "27.maj",
    hours: "15:00",
    img: "img/greenwood.jpg",
    music_performer: "DJ",
    type_of_music: "Studentska zurka",
    reservation: "069/111/106",
  },

  {
    city: "Niksic",
    name: "Sasa Kovacevic",
    location: "Trg Slobode",
    entry: "Free",
    day: "Nedelja",
    date: "21.Maj",
    hours: "20:00",
    img: "img/sasaKovacevic.jpg",
    music_performer: "Koncert",
    type_of_music: "Pop muzika",
    reservation: "062/982/162",
  },

  {
    city: "Niksic",
    name: "Marella",
    location: "Montenegro Pub",
    entry: "Besplatan",
    day: "Nedelja",
    date: "16.Maj",
    hours: "21:00",
    img: "img/marella.jpg",
    music_performer: "DJ",
    type_of_music: "Stdentska zurka",
    reservation: "069/111/106",
  },

  {
    city: "Niksic",
    name: "Tea Tairovic",
    location: "Exclusive event center",
    entry: "20€",
    day: "Nedelja",
    date: "19. Jun",
    hours: "20:00",
    img: "img/tea.jpg",
    music_performer: "Koncert",
    type_of_music: "Pop muzika",
    reservation: "060/342/453",
  },

  ////////////////////////////////////////////////////////////////////

  {
    city: "Podgorica",
    name: "Kristnja Matanovic",
    location: "Restoran 13. jul",
    entry: "Besplatan",
    day: "Ponedeljak",
    date: "20.Maj",
    hours: "21:00",
    img: "img/restoran.jpg",
    music_performer: "Svirka",
    type_of_music: "Narodna i pop muzika",
    reservation: "069/097/156",
  },

  {
    city: "Podgorica",
    name: "Sako Polumenta",
    location: "Hotel Podgorica",
    entry: "20€",
    day: "Utorak",
    date: "16.Maj",
    hours: "21:00",
    img: "img/polumenta.jpg",
    music_performer: "Koncert",
    type_of_music: "Narodna muzika",
    reservation: "+382/716/211/999",
  },

  {
    city: "Podgorica",
    name: "Dj Ari",
    location: "Libre Cocktail Bar",
    entry: "Besplatan",
    day: "Utorak",
    date: "04.Jun",
    hours: "21:00",
    img: "img/libre.jpg",
    music_performer: "DJ",
    type_of_music: "Pop muzika",
    reservation: "Nema",
  },

  {
    city: "Podgorica",
    name: "Roxxi",
    location: "Irish pub",
    entry: "Besplatan",
    day: "Utorak",
    date: "20.Maj",
    hours: "23:00",
    img: "img/irish.jpg",
    music_performer: "Svirka",
    type_of_music: "Rok muzika",
    reservation: "Nema",
  },
  {
    city: "Podgorica",
    name: "Zeljko Samardzic",
    location: "Trg Nezavisnosti",
    entry: "Besplatan",
    day: "Utorak",
    date: "21.Maj",
    hours: "22:00",
    img: "img/samardzic.jpg",
    music_performer: "Koncert",
    type_of_music: "Pop muzika",
    reservation: "067/821/024",
  },

  {
    city: "Podgorica",
    name: "Nikola, Edi, Andrija",
    location: "Restoran Djedovina",
    entry: "Besplatan",
    day: "Srijeda",
    date: "22.Maj",
    hours: "21:00",
    img: "img/djedovina.jpg",
    music_performer: "Svirka",
    type_of_music: "Narodna muzika",
    reservation: "068/008/286",
  },

  {
    city: "Podgorica",
    name: "Marjan",
    location: "Citaona",
    entry: "Besplatan",
    day: "Srijeda",
    date: "29.Maj",
    hours: "20:00",
    img: "img/zurka.jpg",
    music_performer: "DJ",
    type_of_music: "Pop muzika",
    reservation: "Nema",
  },
  {
    city: "Podgorica",
    name: "Breskvica",
    location: "Cascada night club",
    entry: "15€",
    day: "Cetvrtak",
    date: "23.Maj",
    hours: "21:00",
    img: "img/breskvica.jpg",
    music_performer: "Koncert",
    type_of_music: "Popmuzika",
    reservation: "069/000/452",
  },

  {
    city: "Podgorica",
    name: "Pedja Jovanovic",
    location: "100 Manira Restourant & Bar",
    entry: "10€",
    day: "Cetvrtak",
    date: "16.Maj",
    hours: "22:30",
    img: "img/pedja.jpg",
    music_performer: "Svirka",
    type_of_music: "Narodna muzika",
    reservation: "067/011/915",
  },

  {
    city: "Podgorica",
    name: "DJ Vlaa",
    location: "Mr Stefan Braun",
    entry: "Besplatan",
    day: "Petak",
    date: "17.Maj",
    hours: "21:00",
    img: "img/vlaa.jpg",
    music_performer: "Dj",
    type_of_music: "Narodna muzika i pop muzika",
    reservation: "063/415/876",
  },

  {
    city: "Podgorica",
    name: "Bane Nedovic & Jovan Raicevic",
    location: "100 Manira Restaurant & Club",
    entry: "Besplatan",
    day: "Petak",
    date: "31.Maj",
    hours: "20:00",
    img: "img/100.jpg",
    music_performer: "Svirka",
    type_of_music: "Narodna muzika",
    reservation: "069/298/752",
  },

  {
    city: "Podgorica",
    name: "Visnja Petrovic",
    location: "21 Mne Urban Bistro",
    entry: "15€",
    day: "Petak",
    date: "17.Maj",
    hours: "22:00",
    img: "img/visnja.jpg",
    music_performer: "Svirka",
    type_of_music: "Narodna muzika",
    reservation: "069/021/975",
  },

  {
    city: "Podgorica",
    name: "Dancing Queen Abba Tribute Band",
    location: "Trg Nezavisnosti",
    entry: "Besplatan",
    day: "Petak",
    date: "30.Maj",
    hours: "22:00",
    img: "img/abba.jpg",
    music_performer: "Koncert",
    type_of_music: "Pop muzika",
    reservation: "Nema",
  },

  {
    city: "Podgorica",
    name: "Monika Knezevic",
    location: "WWW",
    entry: "Besplatan",
    day: "Subota",
    date: "25.Maj",
    hours: "21:00",
    img: "img/monika.jpg",
    music_performer: "Svirka",
    type_of_music: "Pop muzika",
    reservation: "067/932/762",
  },

  {
    city: "Podgorica",
    name: "Slobodan Radanovic",
    location: "Hotel Podgorica",
    entry: "20€",
    day: "Subota",
    date: "25.Maj",
    hours: "21:00",
    img: "img/slobodan.jpg",
    music_performer: "Koncert",
    type_of_music: "Narodna muzika",
    reservation: "066/213/999",
  },

  {
    city: "Podgorica",
    name: "Lepa Brena",
    location: "SC Moraca",
    entry: "20€",
    day: "Subota",
    date: "25.Maj",
    hours: "21:00",
    img: "img/brena.jpg",
    music_performer: "Koncert",
    type_of_music: "Tradocionalna narodna i pop muzika",
    reservation: "067/256/121",
  },

  {
    city: "Podgorica",
    name: "Nicim Izazvan",
    location: "Boho Retaurant",
    entry: "15€",
    day: "Subota",
    date: "18.Maj",
    hours: "22:30",
    img: "img/NicimIzazvan.jpg",
    music_performer: "Svirka",
    type_of_music: "Rok muzika",
    reservation: "+382/067/987/878",
  },

  {
    city: "Podgorica",
    name: "4 Seasons Acustic Band",
    location: "WWW",
    entry: "Besplatan",
    day: "Subota",
    date: "18.Maj",
    hours: "20:00",
    img: "img/4seasons.jpg",
    music_performer: "Svirka",
    type_of_music: "Pop muzika",
    reservation: "068/012/523",
  },

  {
    city: "Podgorica",
    name: "DJ Pasixzer",
    location: "Destilerija Pub",
    entry: "Besplatan",
    day: "Subota",
    date: "25.Maj",
    hours: "22:30",
    img: "img/destilerija.jpg",
    music_performer: "DJ",
    type_of_music: "Rok muzika",
    reservation: "Nema",
  },

  {
    city: "Podgorica",
    name: "Ogi & Marko",
    location: "WWW",
    entry: "Besplatan",
    day: "Subota",
    date: "01.Jun",
    hours: "21:00",
    img: "img/www.jpg",
    music_performer: "DJ",
    type_of_music: "Narodna muzika i pop muzika",
    reservation: "Nema",
  },

  {
    city: "Podgorica",
    name: "Stimung Duo",
    location: "Avlia",
    entry: "10€",
    day: "Subota",
    date: "18.Maj",
    hours: "20:00",
    img: "img/avlija.jpg",
    music_performer: "DJ",
    type_of_music: "Narodna muzika",
    reservation: "068/234/065",
  },

  {
    city: "Podgorica",
    name: "DJ Fame",
    location: "English Pub Ragina Glava",
    entry: "Free",
    day: "Nedelja",
    date: "19.Maj",
    hours: "00:00",
    img: "img/ragina.jpg",
    music_performer: "DJ",
    type_of_music: "Narodna i pop muzika",
    reservation: "Nema",
  },

  {
    city: "Podgorica",
    name: "Ivana Martinovic",
    location: "Morrison Pub",
    entry: "Besplatan",
    day: "Nedelja",
    date: "19.Maj",
    hours: "23:00",
    img: "img/morrison.jpg",
    music_performer: "Svirka",
    type_of_music: "Rok muzika",
    reservation: "069/021/986",
  },

  {
    city: "Podgorica",
    name: "Kino Kultura",
    location: "Why Bistro",
    entry: "Besplatan",
    day: "Nedelja",
    date: "02.Jun",
    hours: "21:30",
    img: "img/kino.jpeg",
    music_performer: "Svirka",
    type_of_music: "Narodna muzika",
    reservation: "067/311/321",
  },

  {
    city: "Podgorica",
    name: "Boris Rezek & Marko Milosevic",
    location: "Boho Restaurant",
    entry: "Besplatan",
    day: "Nedelja",
    date: "9.Jun",
    hours: "20:00",
    img: "img/boho.jpg",
    music_performer: "Svirka",
    type_of_music: "Narodna muzika",
    reservation: "067/984/065",
  },

  ////////////////////////////////////////////////////////////////////////////////////////

  {
    city: "Berane",
    name: "Ivana Boom Nikolic",
    location: "Hotel Berane ",
    entry: "10€",
    day: "Subota",
    date: "18.Maj",
    hours: "21:00",
    img: "img/boom.jpg",
    music_performer: "Koncert",
    type_of_music: "Pop muzika",
    reservation: "+382/52680080",
  },

  {
    city: "Berane",
    name: "Barbara Bobak",
    location: "Hotel Berane",
    entry: "20€",
    day: "Subota",
    date: "01.Jun",
    hours: "21:00",
    img: "img/barbara.jpg",
    music_performer: "Koncert",
    type_of_music: "Narodna muzika",
    reservation: "+382/51 680 080",
  },

  {
    city: "Berane",
    name: "Pedja Jovanovic",
    location: "Hotel Berane ",
    entry: "Free",
    day: "Cetvrak",
    date: "21.Maj",
    hours: "21:00",
    img: "img/pedja.jpg",
    music_performer: "Svirka",
    type_of_music: "Narodna muzika",
    reservation: "+382/51 680 080",
  },
  //////////////////////////////////////////////////////////////////////////////

  {
    city: "Plav",
    name: "Dino Heldic",
    location: "Le Baron Lounge Bar",
    entry: "Besplatan",
    day: "Subota",
    date: "18.Maj",
    hours: "21:00",
    img: "img/heldic.jpeg",
    music_performer: "Svirka",
    type_of_music: "Narodna muzika",
    reservation: "069/342/222",
  },

  {
    city: "Plav",
    name: "DJ Perrota",
    location: "Le Baron Lounge Bar",
    entry: "Besplatan",
    day: "Petak",
    date: "17.Maj",
    hours: "21:00",
    img: "img/djj.jpeg",
    music_performer: "DJ",
    type_of_music: "Pop muzika",
    reservation: "Nema",
  },

  {
    city: "Plav",
    name: "Aki Extreme Band",
    location: "Le Baron Lounge Bar",
    entry: "Besplatan",
    day: "Srijeda",
    date: "22.Maj",
    hours: "22:00",
    img: "img/plav.jpg",
    music_performer: "Svirka",
    type_of_music: "Pop muzika",
    reservation: "N098/234/987",
  },
  {
    city: "Plav",
    name: "DJ Andjela",
    location: "Le Baron Lounge Bar",
    entry: "Besplatan",
    day: "Petak",
    date: "17.Maj",
    hours: "21:00",
    img: "img/zurka1.jpg",
    music_performer: "DJ",
    type_of_music: "Pop muzika",
    reservation: "Nema",
  },

  {
    city: "Plav",
    name: "Mahir Mulalic",
    location: "Gradski Trg Plav",
    entry: "Besplatan",
    day: "Subota",
    date: "25.Maj",
    hours: "21:00",
    img: "img/mahir.jpeg",
    music_performer: "Koncert",
    type_of_music: "Pop muzika",
    reservation: "Nema",
  },

  ////////////////////////////////////////////////////////////////////////////////////////

  {
    city: "Bijelo Polje",
    name: "Pavle Sekulic",
    location: "Kornjaca Caffee Bar",
    entry: "Besplatan",
    day: "Subota",
    date: "25.Maj",
    hours: "21:00",
    img: "img/sekulic.jpg",
    music_performer: "Svirka",
    type_of_music: "Pop muzika",
    reservation: "Nema",
  },

  {
    city: "Bijelo Polje",
    name: "DJ Nenad ",
    location: "13 Night club",
    entry: "Besplatan",
    day: "Subota",
    date: "18.Maj",
    hours: "22:00",
    img: "img/13.jpg",
    music_performer: "DJ",
    type_of_music: "Pop muzika",
    reservation: "Nema",
  },

  {
    city: "Bijelo Polje",
    name: "Alen Mukovic",
    location: "Kornjaca Caffee Bar",
    entry: "Besplatan",
    day: "Petak",
    date: "17.Maj",
    hours: "22:30",
    img: "img/alen.jpg",
    music_performer: "Svirka",
    type_of_music: "Narodna muzika",
    reservation: "Nema",
  },

  {
    city: "Bijelo Polje",
    name: "Dilan Puzovic",
    location: "Giardino club lounge bar",
    entry: "Besplatan",
    day: "Petak",
    date: "09.Jun",
    hours: "21:30",
    img: "img/dilan.jpg",
    music_performer: "Svirka",
    type_of_music: "Narodna muzika",
    reservation: "069/940/004",
  },

  {
    city: "Bijelo Polje",
    name: "Mladjen Tosovic",
    location: "Biblioteka",
    entry: "Besplatan",
    day: "Nedelja",
    date: "19.Maj",
    hours: "21:00",
    img: "img/mladjen.jpg",
    music_performer: "Svirka",
    type_of_music: "Pop muzika",
    reservation: "Nema",
  },

  {
    city: "Bijelo Polje",
    name: "Kino Kultura",
    location: "Biblioteka",
    entry: "Besplatan",
    day: "Subota",
    date: "25.Maj",
    hours: "22:00",
    img: "img/kino.jpeg",
    music_performer: "Svirka",
    type_of_music: "Pop muzika",
    reservation: "Nema",
  },

  ////////////////////////////////////////////////////////////////////////////////////////////

  {
    city: "Mojkovac",
    name: "Janko Ristanovic",
    location: "Exit Night Club",
    entry: "Besplatan",
    day: "Subota",
    date: "18.Maj",
    hours: "23:00",
    img: "img/exit.jpg",
    music_performer: "Svirka",
    type_of_music: "Pop muzika",
    reservation: "+382/69 576 544",
  },

  {
    city: "Mojkovac",
    name: "DJ Apollon",
    location: "Exit Night Club",
    entry: "Besplatan",
    day: "Petak",
    date: "17.Maj",
    hours: "23:00",
    img: "img/apollon.jpg",
    music_performer: "DJ",
    type_of_music: "Narodna i pop muzika",
    reservation: "+382/69 576 544",
  },

  //////////////////////////////////////////////////////////////////////////////////

  {
    city: "Pljevlja",
    name: "Danijel & Medan",
    location: "River Gastro Pub",
    entry: "Besplatan",
    day: "Subota",
    date: "18.Maj",
    hours: "21:00",
    img: "img/mans.jpg",
    music_performer: "Svirka",
    type_of_music: "Pop muzika",
    reservation: "+382/69 812 435",
  },

  {
    city: "Pljevlja",
    name: "DJ Krvavatzzz",
    location: "Village Pub",
    entry: "Besplatan",
    day: "Petak",
    date: "17.Maj",
    hours: "21:00",
    img: "img/krvavatzzz.jpg",
    music_performer: "DJ",
    type_of_music: "Tehno",
    reservation: "+382/68 208 250",
  },

  {
    city: "Pljevlja",
    name: "Igor Markovic",
    location: "River",
    entry: "Besplatan",
    day: "Nedelja",
    date: "19.Maj",
    hours: "21:00",
    img: "img/river.jpg",
    music_performer: "Svirka",
    type_of_music: "Narodna muzika",
    reservation: "+382/69 812 435",
  },

  /////////////////////////////////////////////////////////////////////////////////////////////

  {
    city: "Kolasin",
    name: "DJ Nemanja",
    location: "Select Night Club",
    entry: "Besplatan",
    day: "Subota",
    date: "18.Maj",
    hours: "23:00",
    img: "img/nemanja.jpg",
    music_performer: "DJ",
    type_of_music: "Pop muzika",
    reservation: "+382/69 216 594",
  },
  {
    city: "Kolasin",
    name: "DJ Lookoo",
    location: "Select Night Club",
    entry: "Besplatan",
    day: "Nedelja",
    date: "19.Maj",
    hours: "23:00",
    img: "img/looko.jpg",
    music_performer: "DJ",
    type_of_music: "Pop muzika",
    reservation: "+382/69 216 594",
  },

  ///////////////////////////////////////////////////////////////////////////////////////////////////
  {
    city: "Pluzine",
    name: "Sara Jo",
    location: "Pivska prica",
    entry: "Besplatan",
    day: "Subota",
    date: "15.Jun",
    hours: "21:00",
    img: "img/sarajo.jpg",
    music_performer: "Koncert",
    type_of_music: "Pop muzika",
    reservation: "Nema",
  },
  {
    city: "Pluzine",
    name: "Dzenan Loncarevic",
    location: "Pivska prica",
    entry: "Besplatan",
    day: "Subota",
    date: "29.Jun",
    hours: "21:00",
    img: "img/dzenan.jpeg",
    music_performer: "Koncert",
    type_of_music: "Pop muzika",
    reservation: "Nema",
  },
  {
    city: "Pluzine",
    name: "Haris Dzinovic",
    location: "Pivska prica",
    entry: "Besplatan",
    day: "Subota",
    date: "13.Jul",
    hours: "21:00",
    img: "img/haris.jpg",
    music_performer: "Koncert",
    type_of_music: "Narodna muzika",
    reservation: "Nema",
  },

  {
    city: "Pluzine",
    name: "Bajaga i Instruktori",
    location: "Pivska prica",
    entry: "Besplatan",
    day: "Nedelja",
    date: "04.Avgust",
    hours: "21:00",
    img: "img/bajaga.jpg",
    music_performer: "Koncert",
    type_of_music: "Pop muzika",
    reservation: "Nema",
  },

  {
    city: "Pluzine",
    name: "Ana Bekuta",
    location: "Pivska prica",
    entry: "Besplatan",
    day: "Petak",
    date: "16. Avgust",
    hours: "21:00",
    img: "img/bekuta.jpg",
    music_performer: "Koncert",
    type_of_music: "Narodna muzika",
    reservation: "Nema",
  },

  {
    city: "Kotor",
    name: "DJ Sleeg",
    location: "Letrika",
    entry: "Free",
    day: "Subota",
    date: "18. Maj",
    hours: "21:00",
    img: "img/sleg.jpg",
    music_performer: "DJ",
    type_of_music: "Elektronska muzika",
    reservation: "067/461/985",
  },
  {
    city: "Kotor",
    name: "Isidora Nikolić",
    location: "Bocasa Beach & Restaurant",
    entry: "Free",
    day: "Subota",
    date: "18. Maj",
    hours: "19:00",
    img: "img/bocasa.jpg",
    music_performer: "Svirka",
    type_of_music: "Pop muzika",
    reservation: "063/745/827",
  },
  {
    city: "Kotor",
    name: "Breskvica",
    location: "Diskoteka Maximus",
    entry: "10€",
    day: "Subota",
    date: "18. Maj",
    hours: "23:00",
    img: "img/breskvica.jpg",
    music_performer: "Nastup",
    type_of_music: "Folk i pop muzika",
    reservation: "068/581/935",
  },
  {
    city: "Kotor",
    name: "Petar Grašo",
    location: "Trg od oružja",
    entry: "Free",
    day: "Utorak",
    date: "21. Maj",
    hours: "21:00",
    img: "img/graso.jpg/",
    music_performer: "Koncert",
    type_of_music: "Pop muzika",
    reservation: "067/461/985",
  },
  {
    city: "Kotor",
    name: "Dragana Mirković",
    location: "Diskoteka Maximus",
    entry: "15€",
    day: "Subota",
    date: "1. Jun",
    hours: "23:00",
    img: "img/dragana.jpg",
    music_performer: "Nastup",
    type_of_music: "Turbo folk",
    reservation: "068/581/935",
  },
  {
    city: "Kotor",
    name: "Nina Badrić",
    location: "Trg od oružja",
    entry: "Free",
    day: "Srijeda",
    date: "17. Jun",
    hours: "21:00",
    img: "img/badric.jpg",
    music_performer: "Koncert",
    type_of_music: "Pop muzika",
    reservation: "068/581/935",
  },
  {
    city: "Ulcinj",
    name: "Millok",
    location: "Kino Cafe cocktail bar",
    entry: "Besplatan",
    day: "Subota",
    date: "18. Maj",
    hours: "21:00",
    img: "img/millok.jpg",
    music_performer: "DJ",
    type_of_music: "Folk muzika",
    reservation: "067/525/655",
  },
  {
    city: "Ulcinj",
    name: "Džejla Ramović",
    location: "Mala Plaža",
    entry: "Besplatan",
    day: "Utorak",
    date: "21. Maj",
    hours: "21:00",
    img: "img/dzejla.jpg",
    music_performer: "Koncert",
    type_of_music: "Pop muzika",
    reservation: "063/832/415",
  },
  {
    city: "Ulcinj",
    name: "Dragana Mirković",
    location: "Primavera Restaurant",
    entry: "15€",
    day: "Petak",
    date: "31. Maj",
    hours: "21:00",
    img: "img/dragana.jpg",
    music_performer: "Nastup",
    type_of_music: "Turbo folk",
    reservation: "067/525/655",
  },
  {
    city: "Bar",
    name: "Gibonni",
    location: "Plato SC Topolica",
    entry: "Besplatan",
    day: "Utorak",
    date: "21. Maj",
    hours: "21:00",
    img: "img/gibonni.jpg",
    music_performer: "Koncert",
    type_of_music: "Pop muzika",
    reservation: "067/525/655",
  },
  {
    city: "Budva",
    name: "Barbara Bobak",
    location: "Cascada Night Club",
    entry: "10€",
    day: "Srijeda",
    date: "22. Maj",
    hours: "21:00",
    img: "img/barbara.jpg",
    music_performer: "Nastup",
    type_of_music: "Turbo folk",
    reservation: "067/548/255",
  },
  {
    city: "Budva",
    name: "Sloba Radanović",
    location: "Cascada Night Club",
    entry: "10€",
    day: "Četvrtak",
    date: "23. Maj",
    hours: "21:00",
    img: "img/sloba.jpg",
    music_performer: "Nastup",
    type_of_music: "Folk muzika",
    reservation: "067/548/255",
  },
  {
    city: "Budva",
    name: "Edita Aradinović",
    location: "Omnia Night Club",
    entry: "5€",
    day: "Subota",
    date: "25. Maj",
    hours: "23:00",
    img: "img/edita.jpg",
    music_performer: "Nastup",
    type_of_music: "Pop muzika",
    reservation: "063/765/504",
  },
  {
    city: "Budva",
    name: "Breskvica",
    location: "Cascada Night Club",
    entry: "10€",
    day: "Petak",
    date: "24. Maj",
    hours: "21:00",
    img: "img//brreskvica.jpg",
    music_performer: "Nastup",
    type_of_music: "Pop muzika",
    reservation: "067/548/255",
  },
  {
    city: "Budva",
    name: "Aca Lukas",
    location: "Omnia Night Club",
    entry: "20€",
    day: "Ponedeljak",
    date: "20.Maj",
    hours: "23:00",
    img: "img/aca.jpg",
    music_performer: "Nastup",
    type_of_music: "Pop muzika",
    reservation: "063/765/504",
  },
  {
    city: "Herceg Novi",
    name: "Željko Samardžić",
    location: "Kanli Kula",
    entry: "/",
    day: "Ponedeljak",
    date: "29. Jul",
    hours: "22:00",
    img: "img/samardzic.jpg",
    music_performer: "Koncert",
    type_of_music: "Pop i narodna muzika",
    reservation: "067/525/655",
  },
  {
    city: "Herceg Novi",
    name: "Sergej Ćetković",
    location: "Kanli Kula",
    entry: "/",
    day: "Subota",
    date: "3. Avgust",
    hours: "22:00",
    img: "img/sergej.jpg",
    music_performer: "Koncert",
    type_of_music: "Pop muzika",
    reservation: "067/525/655",
  },
  {
    city: "Cetinje",
    name: "Severina & Jadranka Barjaktarović",
    location: "Dvorski trg",
    entry: "/",
    day: "Utorak",
    date: "21. Maj",
    hours: "21:00",
    img: "img/seve.jpg",
    music_performer: "Koncert",
    type_of_music: "Pop muzika",
    reservation: "/",
  },
  {
    city: "Cetinje",
    name: "Kerber",
    location: "Gradski poligon Cetinje",
    entry: "/",
    day: "Petak",
    date: "26. Jul",
    hours: "20:00",
    img: "img/kerber.jpg",
    music_performer: "Koncert",
    type_of_music: "Rok muzika",
    reservation: "/",
  },
  {
    city: "Cetinje",
    name: "Buč Kesidi",
    location: "Gradski poligon Cetinje",
    entry: "/",
    day: "Petak",
    date: "26. Jul",
    hours: "21:00",
    img: "img/buckesidi.jpg",
    music_performer: "Koncert",
    type_of_music: "Pop muzika",
    reservation: "/",
  },
  {
    city: "Cetinje",
    name: "Dubioza kolektiv",
    location: "Gradski poligon Cetinje",
    entry: "/",
    day: "Petak",
    date: "26. Jul",
    hours: "23:00",
    img: "img/dubioza.jpg",
    music_performer: "Koncert",
    type_of_music: "Rege",
    reservation: "/",
  },
  {
    city: "Cetinje",
    name: "Voyage",
    location: "Gradski poligon Cetinje",
    entry: "/",
    day: "Petak/Subota",
    date: "26/27. Jul",
    hours: "00:30",
    img: "img/voyage.jpg",
    music_performer: "Koncert",
    type_of_music: "Pop muzika",
    reservation: "/",
  },
];

export default events;
